### ISSUE TITLE
Most links of the datasets and benchmark does not work

### ISSUE THREAD

**Issue by JingyiXu404** [taozh2017/RGBD-SODsurvey#7]
Very rewarding work!

But the most links for the datasets and the link for benchmark (http://dpfan.net/d3netbenchmark/) does not work
Could you please update them?

Thank you!

**Comment by DengPingFan** [comment]
Hi, 

Please check the new link: https://github.com/DengPingFan/D3NetBenchmark

In addition, other related works are presented here: https://dengpingfan.github.io/

Best,

**Comment by JingyiXu404** [comment]
thank you so much!
